package cn.caam.gs.domain.db.base.entity;

public class MAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_admin.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_admin.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_admin.user_type
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_admin.id
     *
     * @return the value of m_admin.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_admin.id
     *
     * @param id the value for m_admin.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_admin.name
     *
     * @return the value of m_admin.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_admin.name
     *
     * @param name the value for m_admin.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_admin.user_type
     *
     * @return the value of m_admin.user_type
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_admin.user_type
     *
     * @param userType the value for m_admin.user_type
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }
}