package cn.caam.gs.domain.db.base.entity;

public class MAuthCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_auth_code.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_auth_code.auth_method
     *
     * @mbggenerated
     */
    private String authMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_auth_code.recieved_by
     *
     * @mbggenerated
     */
    private String recievedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_auth_code.auth_code
     *
     * @mbggenerated
     */
    private String authCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_auth_code.invalid_date
     *
     * @mbggenerated
     */
    private String invalidDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_auth_code.id
     *
     * @return the value of m_auth_code.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_auth_code.id
     *
     * @param id the value for m_auth_code.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_auth_code.auth_method
     *
     * @return the value of m_auth_code.auth_method
     *
     * @mbggenerated
     */
    public String getAuthMethod() {
        return authMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_auth_code.auth_method
     *
     * @param authMethod the value for m_auth_code.auth_method
     *
     * @mbggenerated
     */
    public void setAuthMethod(String authMethod) {
        this.authMethod = authMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_auth_code.recieved_by
     *
     * @return the value of m_auth_code.recieved_by
     *
     * @mbggenerated
     */
    public String getRecievedBy() {
        return recievedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_auth_code.recieved_by
     *
     * @param recievedBy the value for m_auth_code.recieved_by
     *
     * @mbggenerated
     */
    public void setRecievedBy(String recievedBy) {
        this.recievedBy = recievedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_auth_code.auth_code
     *
     * @return the value of m_auth_code.auth_code
     *
     * @mbggenerated
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_auth_code.auth_code
     *
     * @param authCode the value for m_auth_code.auth_code
     *
     * @mbggenerated
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_auth_code.invalid_date
     *
     * @return the value of m_auth_code.invalid_date
     *
     * @mbggenerated
     */
    public String getInvalidDate() {
        return invalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_auth_code.invalid_date
     *
     * @param invalidDate the value for m_auth_code.invalid_date
     *
     * @mbggenerated
     */
    public void setInvalidDate(String invalidDate) {
        this.invalidDate = invalidDate;
    }
}