package cn.caam.gs.domain.db.base.entity;

public class MFixedValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_fixed_value.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_fixed_value.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_fixed_value.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_fixed_value.show_index
     *
     * @mbggenerated
     */
    private Integer showIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_fixed_value.code
     *
     * @return the value of m_fixed_value.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_fixed_value.code
     *
     * @param code the value for m_fixed_value.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_fixed_value.value
     *
     * @return the value of m_fixed_value.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_fixed_value.value
     *
     * @param value the value for m_fixed_value.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_fixed_value.name
     *
     * @return the value of m_fixed_value.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_fixed_value.name
     *
     * @param name the value for m_fixed_value.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_fixed_value.show_index
     *
     * @return the value of m_fixed_value.show_index
     *
     * @mbggenerated
     */
    public Integer getShowIndex() {
        return showIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_fixed_value.show_index
     *
     * @param showIndex the value for m_fixed_value.show_index
     *
     * @mbggenerated
     */
    public void setShowIndex(Integer showIndex) {
        this.showIndex = showIndex;
    }
}