package cn.caam.gs.domain.db.base.entity;

public class MImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_image.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_image.order_photo_ext
     *
     * @mbggenerated
     */
    private String orderPhotoExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_image.bill_photo_ext
     *
     * @mbggenerated
     */
    private String billPhotoExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_image.order_photo
     *
     * @mbggenerated
     */
    private byte[] orderPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_image.bill_photo
     *
     * @mbggenerated
     */
    private byte[] billPhoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_image.id
     *
     * @return the value of m_image.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_image.id
     *
     * @param id the value for m_image.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_image.order_photo_ext
     *
     * @return the value of m_image.order_photo_ext
     *
     * @mbggenerated
     */
    public String getOrderPhotoExt() {
        return orderPhotoExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_image.order_photo_ext
     *
     * @param orderPhotoExt the value for m_image.order_photo_ext
     *
     * @mbggenerated
     */
    public void setOrderPhotoExt(String orderPhotoExt) {
        this.orderPhotoExt = orderPhotoExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_image.bill_photo_ext
     *
     * @return the value of m_image.bill_photo_ext
     *
     * @mbggenerated
     */
    public String getBillPhotoExt() {
        return billPhotoExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_image.bill_photo_ext
     *
     * @param billPhotoExt the value for m_image.bill_photo_ext
     *
     * @mbggenerated
     */
    public void setBillPhotoExt(String billPhotoExt) {
        this.billPhotoExt = billPhotoExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_image.order_photo
     *
     * @return the value of m_image.order_photo
     *
     * @mbggenerated
     */
    public byte[] getOrderPhoto() {
        return orderPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_image.order_photo
     *
     * @param orderPhoto the value for m_image.order_photo
     *
     * @mbggenerated
     */
    public void setOrderPhoto(byte[] orderPhoto) {
        this.orderPhoto = orderPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_image.bill_photo
     *
     * @return the value of m_image.bill_photo
     *
     * @mbggenerated
     */
    public byte[] getBillPhoto() {
        return billPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_image.bill_photo
     *
     * @param billPhoto the value for m_image.bill_photo
     *
     * @mbggenerated
     */
    public void setBillPhoto(byte[] billPhoto) {
        this.billPhoto = billPhoto;
    }
}