package cn.caam.gs.domain.db.base.entity;

public class MMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_message.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_message.msg_type
     *
     * @mbggenerated
     */
    private String msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_message.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_message.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_message.regist_date
     *
     * @mbggenerated
     */
    private String registDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_message.msg
     *
     * @mbggenerated
     */
    private String msg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_message.id
     *
     * @return the value of m_message.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_message.id
     *
     * @param id the value for m_message.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_message.msg_type
     *
     * @return the value of m_message.msg_type
     *
     * @mbggenerated
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_message.msg_type
     *
     * @param msgType the value for m_message.msg_type
     *
     * @mbggenerated
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_message.user_id
     *
     * @return the value of m_message.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_message.user_id
     *
     * @param userId the value for m_message.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_message.title
     *
     * @return the value of m_message.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_message.title
     *
     * @param title the value for m_message.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_message.regist_date
     *
     * @return the value of m_message.regist_date
     *
     * @mbggenerated
     */
    public String getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_message.regist_date
     *
     * @param registDate the value for m_message.regist_date
     *
     * @mbggenerated
     */
    public void setRegistDate(String registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_message.msg
     *
     * @return the value of m_message.msg
     *
     * @mbggenerated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_message.msg
     *
     * @param msg the value for m_message.msg
     *
     * @mbggenerated
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }
}