package cn.caam.gs.domain.db.base.entity;

public class MSmsConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_config.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_config.template_type
     *
     * @mbggenerated
     */
    private String templateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_config.template_id
     *
     * @mbggenerated
     */
    private String templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_config.template_name
     *
     * @mbggenerated
     */
    private String templateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_config.api_url
     *
     * @mbggenerated
     */
    private String apiUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_config.app_key
     *
     * @mbggenerated
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_config.app_secret
     *
     * @mbggenerated
     */
    private String appSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_config.sender
     *
     * @mbggenerated
     */
    private String sender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_config.signature
     *
     * @mbggenerated
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_config.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_config.created_at
     *
     * @mbggenerated
     */
    private String createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_config.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_config.updated_at
     *
     * @mbggenerated
     */
    private String updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_config.id
     *
     * @return the value of m_sms_config.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_config.id
     *
     * @param id the value for m_sms_config.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_config.template_type
     *
     * @return the value of m_sms_config.template_type
     *
     * @mbggenerated
     */
    public String getTemplateType() {
        return templateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_config.template_type
     *
     * @param templateType the value for m_sms_config.template_type
     *
     * @mbggenerated
     */
    public void setTemplateType(String templateType) {
        this.templateType = templateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_config.template_id
     *
     * @return the value of m_sms_config.template_id
     *
     * @mbggenerated
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_config.template_id
     *
     * @param templateId the value for m_sms_config.template_id
     *
     * @mbggenerated
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_config.template_name
     *
     * @return the value of m_sms_config.template_name
     *
     * @mbggenerated
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_config.template_name
     *
     * @param templateName the value for m_sms_config.template_name
     *
     * @mbggenerated
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_config.api_url
     *
     * @return the value of m_sms_config.api_url
     *
     * @mbggenerated
     */
    public String getApiUrl() {
        return apiUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_config.api_url
     *
     * @param apiUrl the value for m_sms_config.api_url
     *
     * @mbggenerated
     */
    public void setApiUrl(String apiUrl) {
        this.apiUrl = apiUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_config.app_key
     *
     * @return the value of m_sms_config.app_key
     *
     * @mbggenerated
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_config.app_key
     *
     * @param appKey the value for m_sms_config.app_key
     *
     * @mbggenerated
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_config.app_secret
     *
     * @return the value of m_sms_config.app_secret
     *
     * @mbggenerated
     */
    public String getAppSecret() {
        return appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_config.app_secret
     *
     * @param appSecret the value for m_sms_config.app_secret
     *
     * @mbggenerated
     */
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_config.sender
     *
     * @return the value of m_sms_config.sender
     *
     * @mbggenerated
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_config.sender
     *
     * @param sender the value for m_sms_config.sender
     *
     * @mbggenerated
     */
    public void setSender(String sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_config.signature
     *
     * @return the value of m_sms_config.signature
     *
     * @mbggenerated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_config.signature
     *
     * @param signature the value for m_sms_config.signature
     *
     * @mbggenerated
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_config.created_by
     *
     * @return the value of m_sms_config.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_config.created_by
     *
     * @param createdBy the value for m_sms_config.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_config.created_at
     *
     * @return the value of m_sms_config.created_at
     *
     * @mbggenerated
     */
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_config.created_at
     *
     * @param createdAt the value for m_sms_config.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_config.updated_by
     *
     * @return the value of m_sms_config.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_config.updated_by
     *
     * @param updatedBy the value for m_sms_config.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_config.updated_at
     *
     * @return the value of m_sms_config.updated_at
     *
     * @mbggenerated
     */
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_config.updated_at
     *
     * @param updatedAt the value for m_sms_config.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }
}