package cn.caam.gs.domain.db.base.entity;

public class MSystemConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_config.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_config.opening_bank
     *
     * @mbggenerated
     */
    private String openingBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_config.account_name
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_config.account_number
     *
     * @mbggenerated
     */
    private String accountNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_config.credit_code
     *
     * @mbggenerated
     */
    private String creditCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_config.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_config.created_at
     *
     * @mbggenerated
     */
    private String createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_config.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_config.updated_at
     *
     * @mbggenerated
     */
    private String updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_config.pay_qrcode
     *
     * @mbggenerated
     */
    private byte[] payQrcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_config.id
     *
     * @return the value of m_system_config.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_config.id
     *
     * @param id the value for m_system_config.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_config.opening_bank
     *
     * @return the value of m_system_config.opening_bank
     *
     * @mbggenerated
     */
    public String getOpeningBank() {
        return openingBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_config.opening_bank
     *
     * @param openingBank the value for m_system_config.opening_bank
     *
     * @mbggenerated
     */
    public void setOpeningBank(String openingBank) {
        this.openingBank = openingBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_config.account_name
     *
     * @return the value of m_system_config.account_name
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_config.account_name
     *
     * @param accountName the value for m_system_config.account_name
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_config.account_number
     *
     * @return the value of m_system_config.account_number
     *
     * @mbggenerated
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_config.account_number
     *
     * @param accountNumber the value for m_system_config.account_number
     *
     * @mbggenerated
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_config.credit_code
     *
     * @return the value of m_system_config.credit_code
     *
     * @mbggenerated
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_config.credit_code
     *
     * @param creditCode the value for m_system_config.credit_code
     *
     * @mbggenerated
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_config.created_by
     *
     * @return the value of m_system_config.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_config.created_by
     *
     * @param createdBy the value for m_system_config.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_config.created_at
     *
     * @return the value of m_system_config.created_at
     *
     * @mbggenerated
     */
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_config.created_at
     *
     * @param createdAt the value for m_system_config.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_config.updated_by
     *
     * @return the value of m_system_config.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_config.updated_by
     *
     * @param updatedBy the value for m_system_config.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_config.updated_at
     *
     * @return the value of m_system_config.updated_at
     *
     * @mbggenerated
     */
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_config.updated_at
     *
     * @param updatedAt the value for m_system_config.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_config.pay_qrcode
     *
     * @return the value of m_system_config.pay_qrcode
     *
     * @mbggenerated
     */
    public byte[] getPayQrcode() {
        return payQrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_config.pay_qrcode
     *
     * @param payQrcode the value for m_system_config.pay_qrcode
     *
     * @mbggenerated
     */
    public void setPayQrcode(byte[] payQrcode) {
        this.payQrcode = payQrcode;
    }
}