package cn.caam.gs.domain.db.base.entity;

public class MUserCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_card.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_card.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_card.valid_status
     *
     * @mbggenerated
     */
    private String validStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_card.valid_start_date
     *
     * @mbggenerated
     */
    private String validStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_card.valid_end_date
     *
     * @mbggenerated
     */
    private String validEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_card.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_card.created_at
     *
     * @mbggenerated
     */
    private String createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_card.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_card.updated_at
     *
     * @mbggenerated
     */
    private String updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_card.id
     *
     * @return the value of m_user_card.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_card.id
     *
     * @param id the value for m_user_card.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_card.user_id
     *
     * @return the value of m_user_card.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_card.user_id
     *
     * @param userId the value for m_user_card.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_card.valid_status
     *
     * @return the value of m_user_card.valid_status
     *
     * @mbggenerated
     */
    public String getValidStatus() {
        return validStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_card.valid_status
     *
     * @param validStatus the value for m_user_card.valid_status
     *
     * @mbggenerated
     */
    public void setValidStatus(String validStatus) {
        this.validStatus = validStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_card.valid_start_date
     *
     * @return the value of m_user_card.valid_start_date
     *
     * @mbggenerated
     */
    public String getValidStartDate() {
        return validStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_card.valid_start_date
     *
     * @param validStartDate the value for m_user_card.valid_start_date
     *
     * @mbggenerated
     */
    public void setValidStartDate(String validStartDate) {
        this.validStartDate = validStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_card.valid_end_date
     *
     * @return the value of m_user_card.valid_end_date
     *
     * @mbggenerated
     */
    public String getValidEndDate() {
        return validEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_card.valid_end_date
     *
     * @param validEndDate the value for m_user_card.valid_end_date
     *
     * @mbggenerated
     */
    public void setValidEndDate(String validEndDate) {
        this.validEndDate = validEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_card.created_by
     *
     * @return the value of m_user_card.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_card.created_by
     *
     * @param createdBy the value for m_user_card.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_card.created_at
     *
     * @return the value of m_user_card.created_at
     *
     * @mbggenerated
     */
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_card.created_at
     *
     * @param createdAt the value for m_user_card.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_card.updated_by
     *
     * @return the value of m_user_card.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_card.updated_by
     *
     * @param updatedBy the value for m_user_card.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_card.updated_at
     *
     * @return the value of m_user_card.updated_at
     *
     * @mbggenerated
     */
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_card.updated_at
     *
     * @param updatedAt the value for m_user_card.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }
}