package cn.caam.gs.domain.db.base.entity;

public class MUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.user_type
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.membership_path
     *
     * @mbggenerated
     */
    private String membershipPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.focus_on
     *
     * @mbggenerated
     */
    private String focusOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.birth
     *
     * @mbggenerated
     */
    private String birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.nationality
     *
     * @mbggenerated
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.political
     *
     * @mbggenerated
     */
    private String political;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.edu_degree
     *
     * @mbggenerated
     */
    private String eduDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.bachelor
     *
     * @mbggenerated
     */
    private String bachelor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.employer
     *
     * @mbggenerated
     */
    private String employer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.employer_type
     *
     * @mbggenerated
     */
    private String employerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.job_title
     *
     * @mbggenerated
     */
    private String jobTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.certificate_type
     *
     * @mbggenerated
     */
    private String certificateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.certificate_code
     *
     * @mbggenerated
     */
    private String certificateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.area_sub
     *
     * @mbggenerated
     */
    private String areaSub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.postal_code
     *
     * @mbggenerated
     */
    private String postalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.mail
     *
     * @mbggenerated
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.check_date
     *
     * @mbggenerated
     */
    private String checkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.check_status
     *
     * @mbggenerated
     */
    private String checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.valid_status
     *
     * @mbggenerated
     */
    private String validStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.regist_date
     *
     * @mbggenerated
     */
    private String registDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.valid_start_date
     *
     * @mbggenerated
     */
    private String validStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.valid_end_date
     *
     * @mbggenerated
     */
    private String validEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.society_type
     *
     * @mbggenerated
     */
    private String societyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.credit_code
     *
     * @mbggenerated
     */
    private String creditCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.application_date
     *
     * @mbggenerated
     */
    private String applicationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.created_at
     *
     * @mbggenerated
     */
    private String createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.updated_at
     *
     * @mbggenerated
     */
    private String updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.id
     *
     * @return the value of m_user.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.id
     *
     * @param id the value for m_user.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.name
     *
     * @return the value of m_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.name
     *
     * @param name the value for m_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.user_type
     *
     * @return the value of m_user.user_type
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.user_type
     *
     * @param userType the value for m_user.user_type
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.password
     *
     * @return the value of m_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.password
     *
     * @param password the value for m_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.membership_path
     *
     * @return the value of m_user.membership_path
     *
     * @mbggenerated
     */
    public String getMembershipPath() {
        return membershipPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.membership_path
     *
     * @param membershipPath the value for m_user.membership_path
     *
     * @mbggenerated
     */
    public void setMembershipPath(String membershipPath) {
        this.membershipPath = membershipPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.focus_on
     *
     * @return the value of m_user.focus_on
     *
     * @mbggenerated
     */
    public String getFocusOn() {
        return focusOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.focus_on
     *
     * @param focusOn the value for m_user.focus_on
     *
     * @mbggenerated
     */
    public void setFocusOn(String focusOn) {
        this.focusOn = focusOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.sex
     *
     * @return the value of m_user.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.sex
     *
     * @param sex the value for m_user.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.birth
     *
     * @return the value of m_user.birth
     *
     * @mbggenerated
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.birth
     *
     * @param birth the value for m_user.birth
     *
     * @mbggenerated
     */
    public void setBirth(String birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.nationality
     *
     * @return the value of m_user.nationality
     *
     * @mbggenerated
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.nationality
     *
     * @param nationality the value for m_user.nationality
     *
     * @mbggenerated
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.political
     *
     * @return the value of m_user.political
     *
     * @mbggenerated
     */
    public String getPolitical() {
        return political;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.political
     *
     * @param political the value for m_user.political
     *
     * @mbggenerated
     */
    public void setPolitical(String political) {
        this.political = political;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.edu_degree
     *
     * @return the value of m_user.edu_degree
     *
     * @mbggenerated
     */
    public String getEduDegree() {
        return eduDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.edu_degree
     *
     * @param eduDegree the value for m_user.edu_degree
     *
     * @mbggenerated
     */
    public void setEduDegree(String eduDegree) {
        this.eduDegree = eduDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.bachelor
     *
     * @return the value of m_user.bachelor
     *
     * @mbggenerated
     */
    public String getBachelor() {
        return bachelor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.bachelor
     *
     * @param bachelor the value for m_user.bachelor
     *
     * @mbggenerated
     */
    public void setBachelor(String bachelor) {
        this.bachelor = bachelor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.position
     *
     * @return the value of m_user.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.position
     *
     * @param position the value for m_user.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.employer
     *
     * @return the value of m_user.employer
     *
     * @mbggenerated
     */
    public String getEmployer() {
        return employer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.employer
     *
     * @param employer the value for m_user.employer
     *
     * @mbggenerated
     */
    public void setEmployer(String employer) {
        this.employer = employer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.employer_type
     *
     * @return the value of m_user.employer_type
     *
     * @mbggenerated
     */
    public String getEmployerType() {
        return employerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.employer_type
     *
     * @param employerType the value for m_user.employer_type
     *
     * @mbggenerated
     */
    public void setEmployerType(String employerType) {
        this.employerType = employerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.job_title
     *
     * @return the value of m_user.job_title
     *
     * @mbggenerated
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.job_title
     *
     * @param jobTitle the value for m_user.job_title
     *
     * @mbggenerated
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.certificate_type
     *
     * @return the value of m_user.certificate_type
     *
     * @mbggenerated
     */
    public String getCertificateType() {
        return certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.certificate_type
     *
     * @param certificateType the value for m_user.certificate_type
     *
     * @mbggenerated
     */
    public void setCertificateType(String certificateType) {
        this.certificateType = certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.certificate_code
     *
     * @return the value of m_user.certificate_code
     *
     * @mbggenerated
     */
    public String getCertificateCode() {
        return certificateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.certificate_code
     *
     * @param certificateCode the value for m_user.certificate_code
     *
     * @mbggenerated
     */
    public void setCertificateCode(String certificateCode) {
        this.certificateCode = certificateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.area
     *
     * @return the value of m_user.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.area
     *
     * @param area the value for m_user.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.area_sub
     *
     * @return the value of m_user.area_sub
     *
     * @mbggenerated
     */
    public String getAreaSub() {
        return areaSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.area_sub
     *
     * @param areaSub the value for m_user.area_sub
     *
     * @mbggenerated
     */
    public void setAreaSub(String areaSub) {
        this.areaSub = areaSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.address
     *
     * @return the value of m_user.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.address
     *
     * @param address the value for m_user.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.postal_code
     *
     * @return the value of m_user.postal_code
     *
     * @mbggenerated
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.postal_code
     *
     * @param postalCode the value for m_user.postal_code
     *
     * @mbggenerated
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.phone
     *
     * @return the value of m_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.phone
     *
     * @param phone the value for m_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.mail
     *
     * @return the value of m_user.mail
     *
     * @mbggenerated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.mail
     *
     * @param mail the value for m_user.mail
     *
     * @mbggenerated
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.check_date
     *
     * @return the value of m_user.check_date
     *
     * @mbggenerated
     */
    public String getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.check_date
     *
     * @param checkDate the value for m_user.check_date
     *
     * @mbggenerated
     */
    public void setCheckDate(String checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.check_status
     *
     * @return the value of m_user.check_status
     *
     * @mbggenerated
     */
    public String getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.check_status
     *
     * @param checkStatus the value for m_user.check_status
     *
     * @mbggenerated
     */
    public void setCheckStatus(String checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.valid_status
     *
     * @return the value of m_user.valid_status
     *
     * @mbggenerated
     */
    public String getValidStatus() {
        return validStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.valid_status
     *
     * @param validStatus the value for m_user.valid_status
     *
     * @mbggenerated
     */
    public void setValidStatus(String validStatus) {
        this.validStatus = validStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.regist_date
     *
     * @return the value of m_user.regist_date
     *
     * @mbggenerated
     */
    public String getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.regist_date
     *
     * @param registDate the value for m_user.regist_date
     *
     * @mbggenerated
     */
    public void setRegistDate(String registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.valid_start_date
     *
     * @return the value of m_user.valid_start_date
     *
     * @mbggenerated
     */
    public String getValidStartDate() {
        return validStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.valid_start_date
     *
     * @param validStartDate the value for m_user.valid_start_date
     *
     * @mbggenerated
     */
    public void setValidStartDate(String validStartDate) {
        this.validStartDate = validStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.valid_end_date
     *
     * @return the value of m_user.valid_end_date
     *
     * @mbggenerated
     */
    public String getValidEndDate() {
        return validEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.valid_end_date
     *
     * @param validEndDate the value for m_user.valid_end_date
     *
     * @mbggenerated
     */
    public void setValidEndDate(String validEndDate) {
        this.validEndDate = validEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.society_type
     *
     * @return the value of m_user.society_type
     *
     * @mbggenerated
     */
    public String getSocietyType() {
        return societyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.society_type
     *
     * @param societyType the value for m_user.society_type
     *
     * @mbggenerated
     */
    public void setSocietyType(String societyType) {
        this.societyType = societyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.group_name
     *
     * @return the value of m_user.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.group_name
     *
     * @param groupName the value for m_user.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.credit_code
     *
     * @return the value of m_user.credit_code
     *
     * @mbggenerated
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.credit_code
     *
     * @param creditCode the value for m_user.credit_code
     *
     * @mbggenerated
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.application_date
     *
     * @return the value of m_user.application_date
     *
     * @mbggenerated
     */
    public String getApplicationDate() {
        return applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.application_date
     *
     * @param applicationDate the value for m_user.application_date
     *
     * @mbggenerated
     */
    public void setApplicationDate(String applicationDate) {
        this.applicationDate = applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.deleted
     *
     * @return the value of m_user.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.deleted
     *
     * @param deleted the value for m_user.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.created_by
     *
     * @return the value of m_user.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.created_by
     *
     * @param createdBy the value for m_user.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.created_at
     *
     * @return the value of m_user.created_at
     *
     * @mbggenerated
     */
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.created_at
     *
     * @param createdAt the value for m_user.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.updated_by
     *
     * @return the value of m_user.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.updated_by
     *
     * @param updatedBy the value for m_user.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.updated_at
     *
     * @return the value of m_user.updated_at
     *
     * @mbggenerated
     */
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.updated_at
     *
     * @param updatedAt the value for m_user.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }
}