package cn.caam.gs.domain.db.base.entity;

import java.math.BigDecimal;

public class MUserTypeSettings {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_type_settings.user_type
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_type_settings.fee_amount
     *
     * @mbggenerated
     */
    private BigDecimal feeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_type_settings.effective_year
     *
     * @mbggenerated
     */
    private Integer effectiveYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_type_settings.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_type_settings.created_at
     *
     * @mbggenerated
     */
    private String createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_type_settings.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_type_settings.updated_at
     *
     * @mbggenerated
     */
    private String updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_type_settings.user_type
     *
     * @return the value of m_user_type_settings.user_type
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_type_settings.user_type
     *
     * @param userType the value for m_user_type_settings.user_type
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_type_settings.fee_amount
     *
     * @return the value of m_user_type_settings.fee_amount
     *
     * @mbggenerated
     */
    public BigDecimal getFeeAmount() {
        return feeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_type_settings.fee_amount
     *
     * @param feeAmount the value for m_user_type_settings.fee_amount
     *
     * @mbggenerated
     */
    public void setFeeAmount(BigDecimal feeAmount) {
        this.feeAmount = feeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_type_settings.effective_year
     *
     * @return the value of m_user_type_settings.effective_year
     *
     * @mbggenerated
     */
    public Integer getEffectiveYear() {
        return effectiveYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_type_settings.effective_year
     *
     * @param effectiveYear the value for m_user_type_settings.effective_year
     *
     * @mbggenerated
     */
    public void setEffectiveYear(Integer effectiveYear) {
        this.effectiveYear = effectiveYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_type_settings.created_by
     *
     * @return the value of m_user_type_settings.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_type_settings.created_by
     *
     * @param createdBy the value for m_user_type_settings.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_type_settings.created_at
     *
     * @return the value of m_user_type_settings.created_at
     *
     * @mbggenerated
     */
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_type_settings.created_at
     *
     * @param createdAt the value for m_user_type_settings.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_type_settings.updated_by
     *
     * @return the value of m_user_type_settings.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_type_settings.updated_by
     *
     * @param updatedBy the value for m_user_type_settings.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_type_settings.updated_at
     *
     * @return the value of m_user_type_settings.updated_at
     *
     * @mbggenerated
     */
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_type_settings.updated_at
     *
     * @param updatedAt the value for m_user_type_settings.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }
}