package cn.caam.gs.domain.db.base.entity;

public class MUserExtend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_extend.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_extend.introducer1
     *
     * @mbggenerated
     */
    private String introducer1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_extend.introducer2
     *
     * @mbggenerated
     */
    private String introducer2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_extend.major
     *
     * @mbggenerated
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_extend.research_dir
     *
     * @mbggenerated
     */
    private String researchDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_extend.learn_experience
     *
     * @mbggenerated
     */
    private String learnExperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_extend.work_experience
     *
     * @mbggenerated
     */
    private String workExperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_extend.papers
     *
     * @mbggenerated
     */
    private String papers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_extend.honors
     *
     * @mbggenerated
     */
    private String honors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_extend.id_photo
     *
     * @mbggenerated
     */
    private byte[] idPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_extend.educational_at
     *
     * @mbggenerated
     */
    private byte[] educationalAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_extend.bachelor_at
     *
     * @mbggenerated
     */
    private byte[] bachelorAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_extend.vocational_at
     *
     * @mbggenerated
     */
    private byte[] vocationalAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_extend.id
     *
     * @return the value of m_user_extend.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_extend.id
     *
     * @param id the value for m_user_extend.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_extend.introducer1
     *
     * @return the value of m_user_extend.introducer1
     *
     * @mbggenerated
     */
    public String getIntroducer1() {
        return introducer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_extend.introducer1
     *
     * @param introducer1 the value for m_user_extend.introducer1
     *
     * @mbggenerated
     */
    public void setIntroducer1(String introducer1) {
        this.introducer1 = introducer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_extend.introducer2
     *
     * @return the value of m_user_extend.introducer2
     *
     * @mbggenerated
     */
    public String getIntroducer2() {
        return introducer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_extend.introducer2
     *
     * @param introducer2 the value for m_user_extend.introducer2
     *
     * @mbggenerated
     */
    public void setIntroducer2(String introducer2) {
        this.introducer2 = introducer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_extend.major
     *
     * @return the value of m_user_extend.major
     *
     * @mbggenerated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_extend.major
     *
     * @param major the value for m_user_extend.major
     *
     * @mbggenerated
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_extend.research_dir
     *
     * @return the value of m_user_extend.research_dir
     *
     * @mbggenerated
     */
    public String getResearchDir() {
        return researchDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_extend.research_dir
     *
     * @param researchDir the value for m_user_extend.research_dir
     *
     * @mbggenerated
     */
    public void setResearchDir(String researchDir) {
        this.researchDir = researchDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_extend.learn_experience
     *
     * @return the value of m_user_extend.learn_experience
     *
     * @mbggenerated
     */
    public String getLearnExperience() {
        return learnExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_extend.learn_experience
     *
     * @param learnExperience the value for m_user_extend.learn_experience
     *
     * @mbggenerated
     */
    public void setLearnExperience(String learnExperience) {
        this.learnExperience = learnExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_extend.work_experience
     *
     * @return the value of m_user_extend.work_experience
     *
     * @mbggenerated
     */
    public String getWorkExperience() {
        return workExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_extend.work_experience
     *
     * @param workExperience the value for m_user_extend.work_experience
     *
     * @mbggenerated
     */
    public void setWorkExperience(String workExperience) {
        this.workExperience = workExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_extend.papers
     *
     * @return the value of m_user_extend.papers
     *
     * @mbggenerated
     */
    public String getPapers() {
        return papers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_extend.papers
     *
     * @param papers the value for m_user_extend.papers
     *
     * @mbggenerated
     */
    public void setPapers(String papers) {
        this.papers = papers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_extend.honors
     *
     * @return the value of m_user_extend.honors
     *
     * @mbggenerated
     */
    public String getHonors() {
        return honors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_extend.honors
     *
     * @param honors the value for m_user_extend.honors
     *
     * @mbggenerated
     */
    public void setHonors(String honors) {
        this.honors = honors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_extend.id_photo
     *
     * @return the value of m_user_extend.id_photo
     *
     * @mbggenerated
     */
    public byte[] getIdPhoto() {
        return idPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_extend.id_photo
     *
     * @param idPhoto the value for m_user_extend.id_photo
     *
     * @mbggenerated
     */
    public void setIdPhoto(byte[] idPhoto) {
        this.idPhoto = idPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_extend.educational_at
     *
     * @return the value of m_user_extend.educational_at
     *
     * @mbggenerated
     */
    public byte[] getEducationalAt() {
        return educationalAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_extend.educational_at
     *
     * @param educationalAt the value for m_user_extend.educational_at
     *
     * @mbggenerated
     */
    public void setEducationalAt(byte[] educationalAt) {
        this.educationalAt = educationalAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_extend.bachelor_at
     *
     * @return the value of m_user_extend.bachelor_at
     *
     * @mbggenerated
     */
    public byte[] getBachelorAt() {
        return bachelorAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_extend.bachelor_at
     *
     * @param bachelorAt the value for m_user_extend.bachelor_at
     *
     * @mbggenerated
     */
    public void setBachelorAt(byte[] bachelorAt) {
        this.bachelorAt = bachelorAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_extend.vocational_at
     *
     * @return the value of m_user_extend.vocational_at
     *
     * @mbggenerated
     */
    public byte[] getVocationalAt() {
        return vocationalAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_extend.vocational_at
     *
     * @param vocationalAt the value for m_user_extend.vocational_at
     *
     * @mbggenerated
     */
    public void setVocationalAt(byte[] vocationalAt) {
        this.vocationalAt = vocationalAt;
    }
}