####################################################################################################
# Current platform's information.
####################################################################################################

####################################################################################################
# Context path of the application.
####################################################################################################
server:
  servlet:
    session:
      timeout: 86400
#### SPRING ####
spring:
  application:
    name: userManage
  
  profiles: 
    active: dev
  
  messages:
    basename: i18n/message
    cache-duration: -1
    encoding: UTF-8
    
  datasource:
    sqlPath: classpath*:cn/caam/gs/domain/db/**/sql/*.xml
    mode: local-MySQL
    local-MySQL:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #jdbc-url: jdbc:mysql://localhost/shatest
      #username: root
      #password: admin
      jdbc-url: jdbc:mysql://afa397eca7da454e925b9a637c954bbfin01.internal.cn-north-4.mysql.rds.myhuaweicloud.com:3306/shatest
      username: root
      password: XHT2024Pass1
    cloud-MySQL:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #jdbc-url: jdbc:mysql://localhost/shatest
      #username: root
      #password: admin
      jdbc-url: jdbc:mysql://afa397eca7da454e925b9a637c954bbfin01.internal.cn-north-4.mysql.rds.myhuaweicloud.com:3306/shatest
      username: root
      password: XHT2024Pass1
    
  session:
    store-type: none

  mail:
    host: mail.jcbc.jp
    port: 587
    username: syakt@jcbc.jp
    password: Tuf1xrrzyb2p3DBB7JOnjg==
    properties:
      smtp:
       auth: true
       starttls:
         enable: true

  #### SMS ####
  sms:
    #APP接入地址+接口访问URI
    api_url: https://smsapi.cn-north-4.myhuaweicloud.com:443/sms/batchSendSms/v1
    #APP_Key
    app_key: zn7A3K61J3bz808w7671r4Mw0Rl9
    #APP_Secret
    app_secret: 0x1Ey9niYOt4yEv9VvKkcxh1kOaI
    #必填:国内短信签名通道号或国际/港澳台短信通道号
    sender: 1069368924410007625
    #条件必填,国内短信关注,当templateId指定的模板类型为通用模板时生效且必填,必须是已审核通过的,与模板类型一致的签名名称
    template_id: ab64fbafe4c94426aa91e15b9f17a9c1
    #条件必填,国内短信关注,当templateId指定的模板类型为通用模板时生效且必填,必须是已审核通过的,与模板类型一致的签名名称 国际/港澳台短信不用关注该参数
    signature: 华为云短信测试
  ################
    
#### LOGGING ####
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    cn.caam.gs: DEBUG
    cn.caam.gs.domain.db: DEBUG

app:
  domain: http://192.168.2.130:8080

#### MYBATIS ####
mybatis:
  configuration:
    map-underscore-to-camel-case: true 

#### mail attachment FILE PATH ####   
#### CRON ####
# 秒/分/時/日/月/曜日
cron:
  #LOTO7 毎週土曜日のAM 00:00に実行（金抽）
  loto7Cron: 0 0 0 * * 6
  #LOTO6 毎週火、金曜日のAM 00:00に実行（月、木抽）
  loto6Cron: 0 0 0 * * 2,5
  #LOTO6 毎週水曜日のAM 00:00に実行（火抽）
  miniLotoCron: 0 0 0 * * 3
################