####################################################################################################
# Current platform's information.
####################################################################################################

####################################################################################################
# Context path of the application.
####################################################################################################
server:
  servlet:
    session:
      timeout: 1800
  port : 80
#### SPRING ####
spring:
  application:
    name: userManage
  
  profiles: 
    active: dev

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

  messages:
    basename: i18n/message
    cache-duration: -1
    encoding: UTF-8
    
  datasource:
    sqlPath: classpath*:cn/caam/gs/domain/db/**/sql/*.xml
    mode: local-MySQL
    local-MySQL:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost/gansuzhenjiu
      #username: root
      password: admin
      #jdbc-url: jdbc:mysql://afa397eca7da454e925b9a637c954bbfin01.internal.cn-north-4.mysql.rds.myhuaweicloud.com:3306/gansuzhenjiu
      username: root
      #password: XHT2024Pass1
    cloud-MySQL:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #jdbc-url: jdbc:mysql://localhost/shatest
      #username: root
      #password: admin
      jdbc-url: jdbc:mysql://afa397eca7da454e925b9a637c954bbfin01.internal.cn-north-4.mysql.rds.myhuaweicloud.com:3306/gansuzhenjiu
      username: root
      password: XHT2024Pass1
    
  session:
    store-type: none

  mail:
    host: smtp.163.com
    port: 25
    username: guokedong7821
    password: RXSQESCNXNAUCSOS
    from: guokedong7821@163.com
    properties:
      smtp:
       auth: true
       starttls:
         enable: true
    templates:
      regist_authcode_template: mail/regist_authcode.html
    
#### LOGGING ####
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    cn.caam.gs: DEBUG
    cn.caam.gs.domain.db: DEBUG

app:
  domain: http://192.168.2.130:8080

#### MYBATIS ####
mybatis:
  configuration:
    map-underscore-to-camel-case: true 

#### mail attachment FILE PATH ####   
#### CRON ####
# 秒/分/時/日/月/曜日
cron:
  #LOTO7 毎週土曜日のAM 00:00に実行（金抽）
  loto7Cron: 0 0 0 * * 6
  #LOTO6 毎週火、金曜日のAM 00:00に実行（月、木抽）
  loto6Cron: 0 0 0 * * 2,5
  #LOTO6 毎週水曜日のAM 00:00に実行（火抽）
  miniLotoCron: 0 0 0 * * 3
################