package cn.caam.gs.domain.db.base.mapper;

import cn.caam.gs.domain.db.base.entity.MAuthCode;

public interface MAuthCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_auth_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_auth_code
     *
     * @mbggenerated
     */
    int insert(MAuthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_auth_code
     *
     * @mbggenerated
     */
    int insertSelective(MAuthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_auth_code
     *
     * @mbggenerated
     */
    MAuthCode selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_auth_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MAuthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_auth_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MAuthCode record);
}