package cn.caam.gs.domain.db.base.mapper;

import cn.caam.gs.domain.db.base.entity.MFixedValue;
import org.apache.ibatis.annotations.Param;

public interface MFixedValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_fixed_value
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("code") String code, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_fixed_value
     *
     * @mbggenerated
     */
    int insert(MFixedValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_fixed_value
     *
     * @mbggenerated
     */
    int insertSelective(MFixedValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_fixed_value
     *
     * @mbggenerated
     */
    MFixedValue selectByPrimaryKey(@Param("code") String code, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_fixed_value
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MFixedValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_fixed_value
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MFixedValue record);
}