package cn.caam.gs.domain.db.base.mapper;

import cn.caam.gs.domain.db.base.entity.MImage;

public interface MImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_image
     *
     * @mbggenerated
     */
    int insert(MImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_image
     *
     * @mbggenerated
     */
    int insertSelective(MImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_image
     *
     * @mbggenerated
     */
    MImage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(MImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MImage record);
}