package cn.caam.gs.domain.db.base.mapper;

import cn.caam.gs.domain.db.base.entity.MMessageRead;

public interface MMessageReadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_message_read
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_message_read
     *
     * @mbggenerated
     */
    int insert(MMessageRead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_message_read
     *
     * @mbggenerated
     */
    int insertSelective(MMessageRead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_message_read
     *
     * @mbggenerated
     */
    MMessageRead selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_message_read
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MMessageRead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_message_read
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MMessageRead record);
}