package cn.caam.gs.domain.db.base.mapper;

import cn.caam.gs.domain.db.base.entity.MMessage;

public interface MMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_message
     *
     * @mbggenerated
     */
    int insert(MMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_message
     *
     * @mbggenerated
     */
    int insertSelective(MMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_message
     *
     * @mbggenerated
     */
    MMessage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(MMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MMessage record);
}