package cn.caam.gs.domain.db.base.mapper;

import cn.caam.gs.domain.db.base.entity.MOrder;

public interface MOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated
     */
    int insert(MOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated
     */
    int insertSelective(MOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated
     */
    MOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MOrder record);
}