package cn.caam.gs.domain.db.base.mapper;

import cn.caam.gs.domain.db.base.entity.MSmsConfig;

public interface MSmsConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sms_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sms_config
     *
     * @mbggenerated
     */
    int insert(MSmsConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sms_config
     *
     * @mbggenerated
     */
    int insertSelective(MSmsConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sms_config
     *
     * @mbggenerated
     */
    MSmsConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sms_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MSmsConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sms_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MSmsConfig record);
}