package cn.caam.gs.domain.db.base.mapper;

import cn.caam.gs.domain.db.base.entity.MSystemConfig;

public interface MSystemConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_config
     *
     * @mbggenerated
     */
    int insert(MSystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_config
     *
     * @mbggenerated
     */
    int insertSelective(MSystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_config
     *
     * @mbggenerated
     */
    MSystemConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MSystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(MSystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MSystemConfig record);
}