package cn.caam.gs.domain.db.base.mapper;

import cn.caam.gs.domain.db.base.entity.MUser20240907;

public interface MUser20240907Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_20240907
     *
     * @mbggenerated
     */
    int insert(MUser20240907 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_20240907
     *
     * @mbggenerated
     */
    int insertSelective(MUser20240907 record);
}