package cn.caam.gs.domain.db.base.mapper;

import cn.caam.gs.domain.db.base.entity.MUserCheckHistory;

public interface MUserCheckHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_check_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_check_history
     *
     * @mbggenerated
     */
    int insert(MUserCheckHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_check_history
     *
     * @mbggenerated
     */
    int insertSelective(MUserCheckHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_check_history
     *
     * @mbggenerated
     */
    MUserCheckHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_check_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MUserCheckHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_check_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MUserCheckHistory record);
}