package cn.caam.gs.domain.db.base.mapper;

import cn.caam.gs.domain.db.base.entity.MUserCard;

public interface MUserCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_card
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_card
     *
     * @mbggenerated
     */
    int insert(MUserCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_card
     *
     * @mbggenerated
     */
    int insertSelective(MUserCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_card
     *
     * @mbggenerated
     */
    MUserCard selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_card
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MUserCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_card
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MUserCard record);
}